include:
  project: do/gitlab-ci
  file: golang.yml

deploy-release:
  image: jfrog.wosai-inc.com/docker-virtual-prod/golang-builder:1.20
  script:
    - make lint
    - make test
    - make build
  variables:
    GOPROXY: https://goproxy.cn,https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASS}@jfrog.wosai-inc.com/artifactory/api/go/golang-virtual-dev,direct
  artifacts:
    when: on_success
    expire_in: "1 week"
    paths:
      - bin

deploy-tag:
  image: jfrog.wosai-inc.com/docker-virtual-prod/golang-builder:1.20
  script:
    - make build
  variables:
    GOPROXY: https://goproxy.cn,https://${ARTIFACTORY_USER_STAGING}:${ARTIFACTORY_PASS_STAGING}@jfrog.wosai-inc.com/artifactory/api/go/golang-virtual-staging,direct
  artifacts:
    untracked: false
    when: on_success
    expire_in: "1 week"
    paths:
      - bin
